### ISSUE TITLE
Bug for jobs that start/end at same time (for whatever reason)

### ISSUE THREAD

**Issue by shreyb** [opensciencegrid/gracc-reporting#53]
At https://github.com/opensciencegrid/gracc-reporting/blob/master/gracc_reporting/TimeUtils.py#L78, we check to make sure that any report using TimeUtils.get_epoch_time_range_utc_ms(start_time, end_time) has a start_time that's less than the end_time.  This is not a guarantee, as on the grid, some jobs error out immediately, and thus the start_time and end_time are recorded as being the same.

An example is this job:

https://gracc.opensciencegrid.org/kibana/goto/b64b14c95d784ee21c11fbbbf4e779bd
https://fifemon.fnal.gov/kibana/goto/20434b5ea764f963f2aaae373a766659

This job was restarted, and immediately failed, so the GRACC record shows the original start time and end time, but the FNAL Landscape record shows the last attempted start time and end time, which are the same.  

Since we assert 
`assert start_time < end_time`

a report running this fails.  We should allow for the start time to be equal to the end time, and also catch any such error and let a report handle it (rather than just exiting out).

**Comment by shreyb** [comment]
Note:  The error came from running a package, fife_reports, that's built on top of gracc-reporting 2.0, and the traceback is as follows:

``` 
2018-10-29 12:11:54.117366: Error running Job Success Rate Report for uboone. Traceback (most recent call last):
  File "/home/ifmon/sbhat/fife-reports-2.0.3/fife_reports/JobSuccessRateReport.py", line 585, in main
    r.run_report()
  File "/home/ifmon/sbhat/fife-reports-2.0.3/fife_reports/JobSuccessRateReport.py", line 86, in run_report
    self.generate_report_file()
  File "/home/ifmon/sbhat/fife-reports-2.0.3/fife_reports/JobSuccessRateReport.py", line 201, in generate_report_file
    linemap = self._generate_job_linemap(job)
  File "/home/ifmon/sbhat/fife-reports-2.0.3/fife_reports/JobSuccessRateReport.py", line 437, in _generate_job_linemap
    timestamps_exact = TimeUtils.get_epoch_time_range_utc_ms(*jt)
  File "build/bdist.linux-x86_64/egg/gracc_reporting/TimeUtils.py", line 78, in get_epoch_time_range_utc_ms
    assert start_time < end_time
AssertionError
```

In our example, `start_time` and `end_time` are both 1540747395 (2018-10-28 12:23:15 CDT).

**Comment by djw8605** [comment]
Is this as easy as changing the assert to `<=`?

**Comment by shreyb** [comment]
Yep.
